-- Activate the warehouse
USE WAREHOUSE NEWSLETTER_WH;

-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS NEWSLETTER_DB;

-- Use the newsletter database
USE DATABASE NEWSLETTER_DB;

-- Create schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS NEWSLETTER_SCHEMA;

-- Use the newsletter schema
USE SCHEMA NEWSLETTER_SCHEMA;

-- Create Subscribers Table
CREATE TABLE IF NOT EXISTS SUBSCRIBERS (
    SUBSCRIBER_ID VARCHAR(255) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(255),
    SUBSCRIPTION_STATUS VARCHAR(50) DEFAULT 'ACTIVE',
    SIGNUP_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REFERRAL_SOURCE VARCHAR(100),
    TAGS VARCHAR(1000),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create Error Log Table
CREATE TABLE IF NOT EXISTS ERROR_LOG (
    ERROR_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    ERROR_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ERROR_MESSAGE VARCHAR(10000),
    ERROR_CONTEXT VARIANT
);

-- Verify table creation
SHOW TABLES;


select * from SUBSCRIBERS;


